language: php

php:
  - '7.1'
  - '7.2'

matrix:
  allow_failures:
    - php: '7.2'
  fast_finish: true

before_script:
  # Install CodeSniffer for WordPress Coding Standards checks.
  - git clone https://github.com/squizlabs/PHP_CodeSniffer.git php-codesniffer
  # Hop into CodeSniffer directory.
  - cd php-codesniffer
  # Checkout pre 3.x version
  - git checkout tags/2.9.1
  # After CodeSniffer install you should refresh your path.
  - phpenv rehash
  # Go back out of CodeSniffer directory.
  - cd ..

script:
  # Search for PHP syntax errors.
  - find . -path ./php-codesniffer -prune -o \( -name '*.php' \) -exec php -lf {} \;
  - ./php-codesniffer/scripts/phpcs -p -s -v -n . --standard=./codesniffer.ruleset.xml --extensions=php --report=source --report=full

deploy:
  provider: elasticbeanstalk
  access_key_id: $ACCESSKEYID
  secret_access_key: # Technique from https://medium.com/@sommershurbaji/continuous-delivery-with-aws-elastic-beanstalk-and-travis-ci-2dd54754965f
    secure: $SECRETACCESSKEY
  region: us-east-1
  bucket_name: elasticbeanstalk-us-east-1-672626379771
  bucket_path: eb-demo
  app: eb-demo
  env: eb-demo-php
  skip_cleanup: true
  on:
    repo: matt-bernhardt/eb-demo
    branch: master
