branch-defaults:
  default:
    environment: eb-demo-dev2
    group_suffix: null
environment-defaults:
  eb-demo-dev2:
    branch: null
    repository: null
global:
  application_name: eb-demo
  branch: null
  default_ec2_keyname: null
  default_platform: PHP 7.1
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: null
  workspace_type: Application
